featured_tag:
  default: ""
  type: text
  description: "Tag to filter topics to feature on the homepage."

number_of_topics:
  default: 5
  type: integer
  description: "Number of topics to feature on the homepage."

hide_closed_topics:
  default: false
  type: bool
  description: "Hide closed topics from the featured list."

sort_by_created:
  default: false
  type: bool
  description: "Sort topics by creation date instead of activity."

featured_categories:
  default: ""
  type: list
  description: "Pipe-separated IDs of categories to feature."
